### ISSUE TITLE
accessibility.md -- build.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#1]
* Markdown文件：
    * [accessibility.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/accessibility.md)
    * [animation.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/animation.md)
    * [browser-dev-tools.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/browser-dev-tools.md)
    * [browsers.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/browsers.md)
    * [build.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/build.md)
  * PR 地址：#14
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by leviding** [comment]
@StarrierC ok
