### ISSUE TITLE
fd-dev-for.md - myth.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#10]
* Markdown文件：
    * [fd-dev-for.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/fd-dev-for.md)
    * [interview-q.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/interview-q.md)
    * [jobboards.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/jobboards.md)
    * [making-fd.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/making-fd.md)
    * [myth.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/myth.md)
  * PR 地址：#36
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：8 天
  * 校对时间：3 天
  * 翻译积分：8 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xueshuai** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@xueshuai ok

**Comment by yankwan** [comment]
@leviding 校队认领

**Comment by leviding** [comment]
@yankwan ok，下次记得在对应的 pull request 下进行认领哈
