### ISSUE TITLE
salaries.md - team.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#11]
* Markdown文件：
    * [salaries.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/salaries.md)
    * [skills.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/skills.md)
    * [team.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/team.md)
  * PR 地址：#16
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@zhmhhu ok
