### ISSUE TITLE
tech-employed-by-fd.md and types-of-front-end-dev.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#12]
* Markdown文件：
    * [tech-employed-by-fd.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/tech-employed-by-fd.md)
    * [types-of-front-end-dev.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice/types-of-front-end-dev.md)
  * PR 地址：#17
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
翻译认领

**Comment by leviding** [comment]
@CACppuccino ok
