### ISSUE TITLE
accessibility.md - browser.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#19]
* Markdown文件：
    * [accessibility.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/accessibility.md)
    * [animation.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/animation.md)
    * [apps.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/apps.md)
    * [baas.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/baas.md)
    * [browsedocs.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/browsedocs.md)
    * [browser.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/browser.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@zhmhhu ok
