### ISSUE TITLE
cli.md -- dom.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#2]
* Markdown文件：
    * [cli.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/cli.md)
    * [courses.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/courses.md)
    * [cs.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/cs.md)
    * [data-api.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/data-api.md)
    * [direct-learning.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/direct-learning.md)
    * [dns.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/dns.md)
    * [dom.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/dom.md)
  * PR 地址：#13
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wzy816** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@wzy816 ok
