### ISSUE TITLE
charting.md - css.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#20]
* Markdown文件：
    * [charting.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/charting.md)
    * [cms.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/cms.md)
    * [code-editor.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/code-editor.md)
    * [comm.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/comm.md)
    * [css.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/css.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：2 天
  * 翻译积分：4.5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@zhmhhu ok
