### ISSUE TITLE
db.md - graphics.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#21]
* Markdown文件：
    * [db.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/db.md)
    * [deploy.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/deploy.md)
    * [dev-tools.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/dev-tools.md)
    * [diagram.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/diagram.md)
    * [dom.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/dom.md)
    * [error.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/error.md)
    * [find-tools.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/find-tools.md)
    * [fonts.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/fonts.md)
    * [graphics.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/graphics.md)
  * PR 地址：#33
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：1 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@zhmhhu ok
