### ISSUE TITLE
hosting.md - offline.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#22]
* Markdown文件：
    * [hosting.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/hosting.md)
    * [html.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/html.md)
    * [http.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/http.md)
    * [js.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/js.md)
    * [json.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/json.md)
    * [loaders.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/loaders.md)
    * [offline.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/offline.md)
  * PR 地址：#34
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@zhmhhu ok
