### ISSUE TITLE
perf.md - seo.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#23]
* Markdown文件：
    * [perf.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/perf.md)
    * [placeholder.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/placeholder.md)
    * [project-hosting.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/project-hosting.md)
    * [proto.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/proto.md)
    * [pwa.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/pwa.md)
    * [repo.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/repo.md)
    * [security.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/security.md)
    * [seo.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/seo.md)
  * PR 地址：#35
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：2 天
  * 校对时间：1 天
  * 翻译积分：2 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@zhmhhu ok
