### ISSUE TITLE
state.md - uptime.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#24]
* Markdown文件：
    * [state.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/state.md)
    * [static.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/static.md)
    * [svg.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/svg.md)
    * [task.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/task.md)
    * [templates.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/templates.md)
    * [testing.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/testing.md)
    * [ui.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/ui.md)
    * [uptime.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools/uptime.md)
  * PR 地址：#38
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
翻译认领  @leviding

**Comment by leviding** [comment]
@xunge0613 ok
