### ISSUE TITLE
2018.md and README.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#25]
* Markdown文件：
    * [2018.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/2018.md)
    * [README.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/README.md)
  * PR 地址：#37
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by kangkai124** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@kangkai124 ok

**Comment by kangkai124** [comment]
@leviding 翻译完成
