### ISSUE TITLE
SUMMARY.md - practice.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#26]
* Markdown文件：
    * [SUMMARY.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/SUMMARY.md)
    * [frontendmasters.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/frontendmasters.md)
    * [learning.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning.md)
    * [myIntro.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/myIntro.md)
    * [practice.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/practice.md)
  * PR 地址：#40
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@zhmhhu ok

**Comment by leviding** [comment]
@zhmhhu 翻译的怎么样啦

**Comment by yankwan** [comment]
@leviding 申请校对

**Comment by leviding** [comment]
@yankwan ok，下次记得在对应的 pr 下认领校对
