### ISSUE TITLE
recap.md、template.md and tools.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#27]
* Markdown文件：
    * [recap.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/recap.md)
    * [template.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/template.md)
    * [tools.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/tools.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by bambooom** [comment]
只剩一个了...看着也不多, 认领一下~
认领翻译 @leviding

**Comment by leviding** [comment]
@bambooom ok

**Comment by leviding** [comment]
@bambooom 翻译的怎么样啦

**Comment by bambooom** [comment]
@leviding sorry 前两天搞忘了 刚翻了 见 pr

**Comment by leviding** [comment]
@bambooom 哈哈，好的辛苦啦
