### ISSUE TITLE
what-is-a-FD.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#28]
* Markdown文件：
    * [what-is-a-FD.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/what-is-a-FD.md)
  * PR 地址：43
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：3.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Xinmiao-Zhuo** [comment]
翻译认领

**Comment by leviding** [comment]
@realYukiko ok

**Comment by leviding** [comment]
@realYukiko 翻译的怎么样啦

**Comment by leviding** [comment]
@realYukiko 怎么样啦

**Comment by Xinmiao-Zhuo** [comment]
@leviding 翻译完了，准备提交～

**Comment by Xinmiao-Zhuo** [comment]
晚一点补充一下 图片的翻译
