### ISSUE TITLE
fonts.md -- headless-browsers.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#3]
* Markdown文件：
    * [fonts.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/fonts.md)
    * [front-end-apps.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/front-end-apps.md)
    * [front-end.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/front-end.md)
    * [headless-browsers.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/headless-browsers.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Colafornia** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@MechanicianW ok

**Comment by leviding** [comment]
@MechanicianW 翻译的怎么样啦

**Comment by Colafornia** [comment]
@leviding 不好意思，有一点小尾巴一直拖着没弄完😂争取今晚发PR
