### ISSUE TITLE
hosting.md -- http-networks.md 这里有一个图片也需要翻译

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#4]
* Markdown文件：
    * [hosting.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/hosting.md)
    * [html-css.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/html-css.md)
    * [http-networks.md
](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/http-networks.md)
  * PR 地址：
  **注意**：这里有一个图片也需要翻译，自己去 PS 或者通过其他方法制作。一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件。
  ----
  * 翻译时间：9 天
  * 校对时间：3 天
  * 翻译积分：9 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
@leviding 认领

顺便问一下是哪一个图..

**Comment by leviding** [comment]
@lsvih 第一个文件里超级大的那张图，也不一定要 PS 出来，也可以把图上的英文翻译了直接写在图下面也行。

**Comment by lsvih** [comment]
我选择 ps ..

**Comment by lsvih** [comment]
@leviding 这个得延迟2天，才搞定那个图片

**Comment by leviding** [comment]
@lsvih ok 的

**Comment by leviding** [comment]
@lsvih 翻译的怎么样啦

**Comment by lsvih** [comment]
@leviding 忘了提交了...晚上 push
