### ISSUE TITLE
internet.md -- json.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#5]
* Markdown文件：
    * [internet.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/internet.md)
    * [javascript.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/javascript.md)
    * [js-api.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/js-api.md)
    * [json.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/json.md)
  * PR 地址：#42
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunshine940326** [comment]
翻译认领

**Comment by leviding** [comment]
@sunshine940326 ok

**Comment by leviding** [comment]
@sunshine940326 翻译的怎么样啦

**Comment by leviding** [comment]
@sunshine940326 怎么样啦

**Comment by sunshine940326** [comment]
抱歉抱歉，最近比较忙。忘记翻译了，2天内完成
