### ISSUE TITLE
learn-from.md - node.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#6]
* Markdown文件：
    * [learn-from.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/learn-from.md)
    * [module-bundlers-loaders.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/module-bundlers-loaders.md)
    * [module.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/module.md)
    * [multi-device-dev.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/multi-device-dev.md)
    * [news-podcasts.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/news-podcasts.md)
    * [node.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/node.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by xunge0613** [comment]
翻译认领

**Comment by leviding** [comment]
@xunge0613 ok
