### ISSUE TITLE
offline.md - react.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#7]
* Markdown文件：
    * [offline.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/offline.md)
    * [package-manager.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/package-manager.md)
    * [perf.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/perf.md)
    * [pwa.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/pwa.md)
    * [react.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/react.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by yanyixin** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@yanyixin ok
