### ISSUE TITLE
security.md - templates.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#8]
* Markdown文件：
    * [security.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/security.md)
    * [self-direct-learning.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/self-direct-learning.md)
    * [seo.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/seo.md)
    * [state.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/state.md)
    * [static.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/static.md)
    * [templates.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/templates.md)
  * PR 地址：#15
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
翻译认领

**Comment by leviding** [comment]
@CACppuccino ok
