### ISSUE TITLE
test.md - web-api.md

### ISSUE THREAD

**Issue by leviding** [xitu/front-end-handbook-2018#9]
* Markdown文件：
    * [test.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/test.md)
    * [ui-design-patterns.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/ui-design-patterns.md)
    * [version-control.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/version-control.md)
    * [web-api.md](https://github.com/xitu/front-end-handbook-2018/blob/zh-Hans/learning/web-api.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：6 天
  * 校对时间：1 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by zhmhhu** [comment]
翻译认领 @leviding 

这个积分太少了，怪不得这么久没人认领╭(╯^╰)╮

**Comment by leviding** [comment]
@zhmhhu 哈哈哈，写错了，我现在调整好了哈。
